### ISSUE TITLE
View all orders

### ISSUE THREAD

**Issue by jluria** [tourbillon-store/tourbillon#14]
Story: As an admin user, I want to view a list of all orders.

Implementation: an Express route on the backend (GET `/api/orders`) should serve up all the orders in an `AllOrders` component.
 
Admin Panel
Story: As an admin, I want a page to navigate through to do admin things like create/edit/view/delete watches/users/orders.

Implementation: Semantic-ui-react, header on the top with menu on the left and data on right.

**Comment by schai6** [comment]
Using https://github.com/marmelab/admin-on-rest
