### ISSUE TITLE
Log Out of Account

### ISSUE THREAD

**Issue by schai6** [tourbillon-store/tourbillon#2]
As a logged-in user, I want to be able to log out, so that someone else can't just come along and use my account.

Implementation: An Express route on the backend for logging out (`/api/auth/logout`). Remove sensitive data and user-specific info (any current listings, any services signed up for) from the session. Display the home page.

**Comment by schai6** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Log Out of Account](https://trello.com/c/7q6EvhTU/1-log-out-of-account)

**Comment by jluria** [comment]
Provided for us
