### ISSUE TITLE
do not send password and salts to front end for all user

### ISSUE THREAD

**Issue by jemyishai** [tourbillon-store/tourbillon#53]

**Comment by schai6** [comment]
I think this is already done in `/api/users`:
`router.get('/', (req, res, next) => {
  User.findAll({
    // explicitly select only the id and email fields - even though
    // users' passwords are encrypted, it won't help if we just
    // send everything to anyone who asks!
    attributes: ['id', 'email']
  })
    .then(users => res.json(users))
    .catch(next)
})
`
